### ISSUE TITLE
error pulling yesterday's price

### ISSUE THREAD

**Issue by facastagnini** [facastagnini/rpi-lcd-bitcoin-monitor#11]
```Traceback (most recent call last):
  File "/home/federico/chirimbolito/bin/chirimbolito", line 11, in <module>
    sys.exit(run())
  File "/home/federico/chirimbolito/local/lib/python2.7/site-packages/chirimbolito/Chirimbolito.py", line 60, in run
    a = Chirimbolito()
  File "/home/federico/chirimbolito/local/lib/python2.7/site-packages/chirimbolito/Chirimbolito.py", line 28, in __init__
    self.main()
  File "/home/federico/chirimbolito/local/lib/python2.7/site-packages/chirimbolito/Chirimbolito.py", line 56, in main
    self.display.modeUp()
  File "/home/federico/chirimbolito/local/lib/python2.7/site-packages/chirimbolito/ChirimbolitoDisplay.py", line 60, in modeUp
    self.update()
  File "/home/federico/chirimbolito/local/lib/python2.7/site-packages/chirimbolito/ChirimbolitoDisplay.py", line 70, in update
    self.info.refresh()
  File "/home/federico/chirimbolito/local/lib/python2.7/site-packages/chirimbolito/ChirimbolitoInfo.py", line 118, in refresh
    self.checkPriceYesterday()
  File "/home/federico/chirimbolito/local/lib/python2.7/site-packages/chirimbolito/ChirimbolitoInfo.py", line 63, in checkPriceYesterday
    self.priceYesterday = prices_json['bpi'][self.yesterday]
KeyError: 'bpi'
```

**Comment by facastagnini** [comment]
probably fixed when replacing urllib2 with requests #9
